DROP DATABASE  IF EXISTS multipart;

CREATE DATABASE multipart CHAR SET UTF8;
USE multipart;

CREATE TABLE students(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(120) NOT NULL,
last_name VARCHAR(120) NOT NULL,
age INT NOT NULL,
photos VARCHAR(64) NOT NULL
);

SELECT * FROM students;